name: dev branch ci

on:
  pull_request:
    types: [ opened, review_requested ]
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Discord notification(start ci work flow)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: ${{ toJson(DISCORD_BODY) }}
        uses: Ilshidur/action-discord@master
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: check out project
        run: ls -al
        
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: project testing
        run: SPRING_PROFILES_ACTIVE=dev ./gradlew clean build

