name: dev branch ci

on:
  pull_request:
    types: [opened, review_requested]
    branches:
      - 'main'
  workflow_dispatch:
  
env:
  DISCORD_EMBEDS: |
    [{
      "title": "[#${{ github.event.pull_request.number }}] ${{ github.event.pull_request.title }}",
      "author": {
        "name": "${{ github.event.pull_request.user.login }}"
      },
      "url": "${{ github.event.pull_request.html_url }}",
      "color": ##00ff00,
      "description": "${{ github.event.pull_request.body }}"
    }]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: precheck 
        run: |
          echo ${{ env.DISCORD.EMBEDS }}
          echo $env.DISCORD.EMBEDS
        
      - name: Discord notification (start ci workflow)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

        uses: Ilshidur/action-discord@master
        with:
          args: "${{ github.event.pull_request.html_url }} 링크입니다."
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: Check out project
        run: ls -al
        
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Project testing
        run: |
          SPRING_PROFILES_ACTIVE=dev \
          ./gradlew clean build
