name: dev server deploy

on:
  push:
    branchs: ["develop"]

  workflow_dispatch:

env:
  VERSION: ${{github.sha}}
  DOCKER_IMAGE: ghcr.io/slate-movte/cicd-test

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker Layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{runner.os}}-buildx-${{env.version}}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: qudtjs0753
          password: ${{secrets.CICD_REGISTRY}}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{env.DOCKER_IMAGE}}:latest
