name: dev server deploy

on:
  push:
    branches: ["main", "develop"]

  workflow_dispatch:

env:
  VERSION: ${{github.sha}}
  DOCKER_IMAGE: ghcr.io/slate-movte/cicd-test
  NAME: cicd-test
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Project testing
        run: |
          SPRING_PROFILES_ACTIVE=dev \
          ./gradlew clean build
      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker Layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{runner.os}}-buildx-${{env.version}}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: qudtjs0753
          password: ${{secrets.CICD_REGISTRY}}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{env.DOCKER_IMAGE}}:latest
  deploy:
    needs: build-push
    name: Deploy
    runs-on: [self-hosted]
    steps:
      #   - name: Login to docker registry
      #     uses: docker/login-action@v1
      #     with:
      #       registry: ghcr.io
      #       username: qudtjs0753
      #       password: ${{secrets.CICD_REGISTRY}}
      - name: Execute
        id: execute
        run: |
          docker ps
        #   docker stop ${{env.NAME}} && docker rm ${{env.NAME}} && docker rmi ${{env.DOCKER_IMAGE}}:latest
        #     docker run -d -p 8080:8080 --name ${{env.NAME}} ${{env.DOCKER_IMAGE}}:latest

    #   - name: send result when success
    #     needs:
    #     if: ${{success() && steps.execute.conclusion=='success'}}
    #     uses: Ilshidur/action-discord@master
    #     with:
    #       args: "배포 성공입니다"
    #   - name: send result when failure
    #     if: ${{ failure() && steps.execute.conclusion=='failure'}}
    #     uses: Ilshidur/action-discord@master
    #     with:
    #       args: "배포 실패입니다."
