name: dev branch ci

on:
  pull_request:
    types: [opened, review_requested]
    branches:
      - "main"
  workflow_dispatch:

env:
  DISCORD_EMBEDS: |
    [{
      "title": "[#${{ github.event.pull_request.number }}] ${{ github.event.pull_request.title }}",
      "author": {
        "name": "${{ github.event.pull_request.user.login }}"
      },
      "url": "${{ github.event.pull_request.html_url }}",
      "color": 65280,
      "description": "${{ github.event.pull_request.body }}"
    }]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: precheck
        run: |
          echo ${{ env.DISCORD.EMBEDS }}
          echo $env.DISCORD.EMBEDS
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      - name: Discord notification (start ci workflow)
        uses: ./.github/actions/discord_action
        with:
          title: "[#${{ github.event.pull_request.number }}]${{ github.event.pull_request.title }}"
          author: ${{ github.event.pull_request.user.login }}
          webhookurl: ${{ secrets.DISCORD_WEBHOOK }}
          color: 65280
          description: ${{ github.event.pull_request.body }}

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Project testing
        run: |
          SPRING_PROFILES_ACTIVE=dev \
          ./gradlew clean build
