name: dev branch ci

on:
  pull_request:
    types: [ opened, review_requested ]
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: check out project
        run: ls -al

      - name: Set up JDK 17
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: project testing
        run: ./gradlew clean build

