name: dev server deploy

on:
  push:
    branches: ["main", "develop"]

  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: ../actions/discord_noti
        with:
          title: "hh"
          color: 65280
          author: "author"
          description: "안녕하세요"