name: message test

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      - uses: ./.github/actions/discord_noti
        with:
          title: "hh"
          color: 65280
          author: "author"
          description: "안녕하세요"